services:
  postgres:
    image: postgres:16
    restart: always
    container_name: postgres
    networks:
      - source-network
      - spark-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data.dump:/docker-entrypoint-initdb.d/data.dump
      - ./scripts/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
      # - pg-data:/var/lib/postgresql/data

# volumes:
#   pg-data:
networks:
  source-network:
    name: source_network
    driver: bridge
  spark-network:
    name: spark_network
    external: true